apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: '{{ .Release.Name }}'
spec:
  sourceRepos:
    - '{{ $.Values.githubUrl }}/{{ .Values.githubOrg | default .Release.Name }}/*'
  destinations:
    - namespace: '{{ .Release.Name }}-*'
      name: {{ .Values.cluster }}
  roles:
  - name: admin
    policies:
    - p, proj:{{ .Release.Name }}:admin, *, *, {{ .Release.Name }}/*, allow
    groups:
    - '{{ .Values.group }}'

